### ISSUE TITLE
problem with relative imports?

### ISSUE THREAD

**Issue by jparal** [ethronsoft/gcspypi#4]
hi, I gave gcspypi a quick try but im getting following error:

```python
File "/home/user/tmp/gcspypi/ethronsoft/gcspypi/__main__.py", line 5, in <module>
    import pb
ModuleNotFoundError: No module named 'pb'
```
I am no python expert but could it have something to do with relative imports and the actual import should be:
```python
from ethronsoft.gcspypi import pb
```

I am running Python3 so that could also play a role. Thanks.

**Comment by edoardofelici** [comment]
hey, sorry for late reply. As you said, python 3 relative imports work a bit differently. I will release a new version better supporting py3 as soon as I have some time. Thanks for spotting this. Will keep this issue open as reminder.

**Comment by edoardofelici** [comment]
should be ok now. 

Run it as a module python -m ethronsoft.gcspypi from the project root (or better, install it and run from command line exe `gcspypi`)
